[project]
name = "GroundingDINO"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Xiaolin Fang", email = "xiaolinf@mit.edu"},
]
dependencies = [
    "torch",
    "torchvision",
    "transformers",
    "addict",
    "yapf",
    "timm",
    "numpy",
    "opencv-python",
    "supervision>=0.22.0",
    "pycocotools",
    "pdm-backend",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["torch", "pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]

[tool.pdm.build]
run-setuptools = true

# no-isolation since dependencies build PyTorch CUDA extensions
[tool.pdm.options]
add = ["--no-isolation"]
install = ["--no-isolation"]
